// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {ERC20} from "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";

/// @title BNBTokenMakerToken
/// @notice Single-implementation BEP-20 token (ERC-20 interface) generated by
/// BNB Token Maker. No proxies, no upgradeability, no hidden admin, no taxes,
/// no fees, no backdoors. Every optional capability is an immutable
/// construction-time flag; anything not enabled reverts instead of silently
/// doing nothing.
///
/// FEATURE SEMANTICS (each documented here and covered by tests):
/// - BURN: any holder may burn their own tokens via burn()/burnFrom();
///   totalSupply decreases. Burn is always allowed, even while paused? NO —
///   pause blocks ALL balance changes including mint and burn (matches
///   OpenZeppelin Pausable semantics). Burn is exempt from maxTx/maxWallet,
///   blacklist sender-side (a blacklisted holder may still destroy tokens),
///   and whitelist enforcement (burning is an exit, never an entry).
/// - MINT: onlyOwner, only when mintable. Minting increases totalSupply.
///   Mint is blocked while paused. Mint to a blacklisted recipient reverts.
///   While whitelist enforcement is ON, mint recipient must be whitelisted
///   (or owner). Mint bypasses maxTx; mint respects maxWallet unless the
///   recipient is the owner.
/// - PAUSE: onlyOwner pause()/unpause(). While paused, every mint, burn and
///   transfer reverts.
/// - MAX TX: when enabled (maxTxAmount > 0), plain transfers
///   (from != 0 && to != 0) with value > maxTxAmount revert. The owner is
///   exempt as sender AND as recipient so distribution can never deadlock.
///   Mint (from == 0) and burn (to == 0) bypass maxTx.
/// - MAX WALLET: when enabled (maxWalletAmount > 0), any credit to a
///   non-owner recipient (transfer or mint) that would push
///   balanceOf(recipient) + value above maxWalletAmount reverts. The owner
///   as recipient is exempt, so initial-supply deployment can never fail.
///   Burn (to == 0) is exempt. When both limits are enabled the constructor
///   requires maxWalletAmount >= maxTxAmount.
/// - BLACKLIST: onlyOwner setBlacklisted(). A blacklisted address can neither
///   send (except burning to address(0), which stays allowed so funds are
///   never trapped) nor receive (mint to a blacklisted recipient reverts).
///   address(0) can never be blacklisted.
/// - WHITELIST: onlyOwner setWhitelisted()/setWhitelistEnforced(). Restriction
///   starts OFF (open trading) even when the module is enabled, and the owner
///   is auto-whitelisted at construction. While enforcement is ON: plain
/// transfers require sender whitelisted-or-owner AND recipient
/// whitelisted-or-owner; mint requires recipient whitelisted-or-owner;
/// burn stays allowed. The owner qualifies as whitelisted on its own side
/// and can always add entries or disable enforcement, so a misconfigured
/// list can never permanently lock the token — but while enforcement is ON,
/// even the owner must whitelist a recipient before sending to it.
contract BNBTokenMakerToken is ERC20, Ownable {
    // ---- validation boundaries (mirrored in lib/token validation) ----
    uint256 private constant NAME_BYTES_MIN = 1;
    uint256 private constant NAME_BYTES_MAX = 64;
    uint256 private constant SYMBOL_BYTES_MIN = 1;
    uint256 private constant SYMBOL_BYTES_MAX = 11;
    uint8 private constant DECIMALS_MAX = 18;

    // ---- immutable feature flags ----
    bool public immutable burnable;
    bool public immutable mintable;
    bool public immutable pausable;
    uint256 public immutable maxTxAmount; // 0 = disabled
    uint256 public immutable maxWalletAmount; // 0 = disabled
    bool public immutable blacklistEnabled;
    bool public immutable whitelistEnabled;

    uint8 private immutable _decimals;
    bool private _paused;

    mapping(address => bool) private _blacklisted;
    mapping(address => bool) private _whitelisted;
    bool private _whitelistEnforced;

    // ---- errors ----
    error ZeroAddress();
    error EmptyName();
    error NameTooLong();
    error EmptySymbol();
    error InvalidSymbol();
    error DecimalsOutOfRange(uint8 decimals);
    error ZeroInitialSupply();
    error MaxWalletBelowMaxTx(uint256 maxWallet, uint256 maxTx);
    error FeatureDisabled(string feature);
    error EnforcedPause();
    error MaxTxExceeded(uint256 value, uint256 maxTx);
    error MaxWalletExceeded(address account, uint256 balanceAfter, uint256 maxWallet);
    error Blacklisted(address account);
    error WhitelistEnforced();
    error ZeroMintAmount();
    error ZeroBurnAmount();

    event Paused(address indexed account);
    event Unpaused(address indexed account);
    event BlacklistedSet(address indexed account, bool blocked);
    event WhitelistedSet(address indexed account, bool allowed);
    event WhitelistEnforcedSet(bool enforced);

    /// @dev Single-struct constructor argument: avoids stack-too-deep and
    /// keeps the factory call-site unambiguous (no positional drift).
    struct TokenConfig {
        string name;
        string symbol;
        uint8 decimals;
        uint256 initialSupply;
        address owner;
        bool burnable;
        bool mintable;
        bool pausable;
        uint256 maxTxAmount; // 0 = disabled
        uint256 maxWalletAmount; // 0 = disabled
        bool blacklistEnabled;
        bool whitelistEnabled;
    }

    constructor(TokenConfig memory config)
        ERC20(config.name, config.symbol)
        Ownable(config.owner)
    {
        if (config.owner == address(0)) revert ZeroAddress();
        uint256 nameLen = bytes(config.name).length;
        if (nameLen < NAME_BYTES_MIN) revert EmptyName();
        if (nameLen > NAME_BYTES_MAX) revert NameTooLong();
        bytes memory sym = bytes(config.symbol);
        uint256 symbolLen = sym.length;
        if (symbolLen < SYMBOL_BYTES_MIN) revert EmptySymbol();
        if (symbolLen > SYMBOL_BYTES_MAX) revert InvalidSymbol();
        for (uint256 i = 0; i < symbolLen; ++i) {
            bytes1 c = sym[i];
            bool ok =
                (c >= 0x30 && c <= 0x39) || // 0-9
                (c >= 0x41 && c <= 0x5A); // A-Z
            if (!ok) revert InvalidSymbol();
        }
        if (config.decimals > DECIMALS_MAX) revert DecimalsOutOfRange(config.decimals);
        if (config.initialSupply == 0) revert ZeroInitialSupply();
        // A transfer limit is enabled by passing a nonzero amount; passing 0
        // disables it. A nonzero amount IS the flag, so no separate boolean
        // can drift out of sync with the enforced value.
        if (config.maxWalletAmount > 0 && config.maxTxAmount > 0) {
            if (config.maxWalletAmount < config.maxTxAmount) {
                revert MaxWalletBelowMaxTx(config.maxWalletAmount, config.maxTxAmount);
            }
        }

        burnable = config.burnable;
        mintable = config.mintable;
        pausable = config.pausable;
        maxTxAmount = config.maxTxAmount;
        maxWalletAmount = config.maxWalletAmount;
        blacklistEnabled = config.blacklistEnabled;
        whitelistEnabled = config.whitelistEnabled;
        _decimals = config.decimals;

        if (config.whitelistEnabled) {
            // Owner starts whitelisted so enabling enforcement can never lock
            // the deployer out of their own token.
            _whitelisted[config.owner] = true;
        }

        _mint(config.owner, config.initialSupply);
    }

    function decimals() public view override returns (uint8) {
        return _decimals;
    }

    // ---- views ----
    function paused() external view returns (bool) {
        return _paused;
    }

    function isBlacklisted(address account) external view returns (bool) {
        return _blacklisted[account];
    }

    function isWhitelisted(address account) external view returns (bool) {
        return _whitelisted[account];
    }

    function whitelistEnforced() external view returns (bool) {
        return _whitelistEnforced;
    }

    function maxTxEnabled() external view returns (bool) {
        return maxTxAmount > 0;
    }

    function maxWalletEnabled() external view returns (bool) {
        return maxWalletAmount > 0;
    }

    // ---- burn ----
    function burn(uint256 value) external {
        if (!burnable) revert FeatureDisabled("burn");
        if (value == 0) revert ZeroBurnAmount();
        _burn(_msgSender(), value);
    }

    function burnFrom(address account, uint256 value) external {
        if (!burnable) revert FeatureDisabled("burn");
        if (value == 0) revert ZeroBurnAmount();
        _spendAllowance(account, _msgSender(), value);
        _burn(account, value);
    }

    // ---- mint ----
    function mint(address to, uint256 value) external onlyOwner {
        if (!mintable) revert FeatureDisabled("mint");
        if (to == address(0)) revert ZeroAddress();
        if (value == 0) revert ZeroMintAmount();
        _mint(to, value);
    }

    // ---- pause ----
    function pause() external onlyOwner {
        if (!pausable) revert FeatureDisabled("pause");
        _paused = true;
        emit Paused(_msgSender());
    }

    function unpause() external onlyOwner {
        if (!pausable) revert FeatureDisabled("pause");
        _paused = false;
        emit Unpaused(_msgSender());
    }

    // ---- blacklist ----
    function setBlacklisted(address account, bool blocked) external onlyOwner {
        if (!blacklistEnabled) revert FeatureDisabled("blacklist");
        if (account == address(0)) revert ZeroAddress();
        _blacklisted[account] = blocked;
        emit BlacklistedSet(account, blocked);
    }

    // ---- whitelist ----
    function setWhitelisted(address account, bool allowed) external onlyOwner {
        if (!whitelistEnabled) revert FeatureDisabled("whitelist");
        if (account == address(0)) revert ZeroAddress();
        _whitelisted[account] = allowed;
        emit WhitelistedSet(account, allowed);
    }

    function setWhitelistEnforced(bool enforced) external onlyOwner {
        if (!whitelistEnabled) revert FeatureDisabled("whitelist");
        _whitelistEnforced = enforced;
        emit WhitelistEnforcedSet(enforced);
    }

    // ---- transfer hook: all restrictions enforced in one place ----
    function _update(address from, address to, uint256 value) internal override {
        if (_paused) revert EnforcedPause();

        address owner = owner();

        if (blacklistEnabled) {
            if (_blacklisted[from] && to != address(0)) revert Blacklisted(from);
            if (_blacklisted[to]) revert Blacklisted(to);
        }

        if (whitelistEnabled && _whitelistEnforced) {
            if (to == address(0)) {
                // burn: always allowed (exit path).
            } else if (from == address(0)) {
                // mint: recipient must be approved (or owner).
                if (to != owner && !_whitelisted[to]) revert WhitelistEnforced();
            } else {
                if (from != owner && !_whitelisted[from]) revert WhitelistEnforced();
                if (to != owner && !_whitelisted[to]) revert WhitelistEnforced();
            }
        }

        if (from != address(0) && to != address(0)) {
            // plain transfer
            if (maxTxAmount > 0 && from != owner && to != owner) {
                if (value > maxTxAmount) revert MaxTxExceeded(value, maxTxAmount);
            }
            if (maxWalletAmount > 0 && to != owner) {
                uint256 afterBalance = balanceOf(to) + value;
                if (afterBalance > maxWalletAmount) {
                    revert MaxWalletExceeded(to, afterBalance, maxWalletAmount);
                }
            }
        } else if (from == address(0) && to != address(0)) {
            // mint
            if (maxWalletAmount > 0 && to != owner) {
                uint256 afterBalance = balanceOf(to) + value;
                if (afterBalance > maxWalletAmount) {
                    revert MaxWalletExceeded(to, afterBalance, maxWalletAmount);
                }
            }
        }
        // burn (to == 0): no maxTx / maxWallet checks by design.

        super._update(from, to, value);
    }
}
