// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {ERC20} from "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";
import {SwapLib} from "./SwapLib.sol";

/// @title BNBTokenMakerToken
/// @notice Single-implementation BEP-20 token (ERC-20 interface) generated by
/// BNB Token Maker. No proxies, no upgradeability, no hidden admin, no hidden
/// platform tax, no backdoors. Every optional capability is an immutable
/// construction-time choice; anything not enabled reverts instead of silently
/// doing nothing. Heavy swap execution and config validation run
/// delegatecall'd in the external stateless SwapLib (linked at compile time).
///
/// TRUST MODEL: immutable money parameters, mutable operational lists, no
/// platform roles anywhere. The factory holds no reference, no role and no
/// upgrade path over tokens it creates.
///
/// MAXIMUM LIFETIME SUPPLY (not current supply):
/// `maxSupply` is the maximum LIFETIME ISSUANCE in base units — cumulative
/// tokens ever minted, INCLUDING the initial supply and EXCLUDING burns.
/// Burning NEVER restores mint capacity (tracked in `_totalMinted`, which only
/// increases). `maxSupply == 0` is an explicit immutable deployment-time
/// choice of unlimited minting. This is deliberately NOT a cap on current
/// `totalSupply()`: e.g. lifetime cap 10M with 5M burned still forbids any
/// further mint.
contract BNBTokenMakerToken is ERC20, Ownable {
    // ---- PancakeSwap V2 router lives in SwapLib (single source of truth).
    // The token keeps only the router address for receive().
    address private constant ROUTER = 0x10ED43C718714eb63d5aA57B78B54704E256024E;

    /// @notice Non-privileged provenance. Informational only: no authority,
    /// no tracking, no wallet, no upgradability is (or can be) derived from it.
    string public constant GENERATOR = "BNBTokenMaker.com";
    /// @notice Factory that deployed this token (msg.sender at construction).
    /// Unforgeable lineage, zero authority.
    address public immutable FACTORY;

    // ---- immutable feature flags / money parameters ----
    bool public immutable burnable;
    bool public immutable mintable;
    bool public immutable pausable;
    uint256 public immutable maxTxAmount; // 0 = disabled
    uint256 public immutable maxWalletAmount; // 0 = disabled
    bool public immutable blacklistEnabled;
    bool public immutable whitelistEnabled;
    uint256 public immutable buyTaxBps;
    uint256 public immutable sellTaxBps;
    uint256 public immutable swapThreshold;
    uint256 public immutable liquidityShareBps;
    uint256 public immutable marketingShareBps;
    bool public immutable autoLiquidityEnabled;
    bool public immutable antiBotEnabled;
    uint256 public immutable snipeBlocks;
    /// @notice Maximum LIFETIME ISSUANCE (base units). 0 = unlimited minting
    /// as an explicit immutable deployment-time choice. Otherwise immutable:
    /// cumulative minted supply (INCLUDING initial supply, EXCLUDING burns)
    /// can never exceed it — no burn-and-remint loophole by design.
    uint256 public immutable maxSupply;

    uint8 private immutable _decimals;
    bool private _paused;
    bool private _swapping;
    bool private _whitelistEnforced;

    mapping(address => bool) private _blacklisted;
    mapping(address => bool) private _whitelisted;
    mapping(address => bool) private _feeExempt;
    mapping(address => bool) public automatedMarketMakerPairs;
    mapping(address => uint256) private _lastTxBlock;

    address private _marketingWallet;
    bool private _tradingEnabled;
    uint256 private _launchBlock;
    bool private _swapBackEnabled = true;
    /// @notice Cumulative base units ever minted (constructor supply
    /// included). Burns never decrement it.
    uint256 private _totalMinted;

    // ---- errors ----
    error ZeroAddress();
    error ZeroAmount();
    error FeatureDisabled(string feature);
    error EnforcedPause();
    error MaxTxExceeded(uint256 value, uint256 maxTx);
    error MaxWalletExceeded(address account, uint256 balanceAfter, uint256 maxWallet);
    error Blacklisted(address account);
    error PairBlacklisted();
    error WhitelistEnforced();
    error TradingDisabled();
    error TradingAlreadyEnabled();
    error CooldownActive();
    error RouterOnly();
    error MaxSupplyExceeded(uint256 mintedAfter, uint256 maxSupply);

    event Paused(address indexed account);
    event Unpaused(address indexed account);
    event BlacklistedSet(address indexed account, bool blocked);
    event WhitelistedSet(address indexed account, bool allowed);
    event WhitelistEnforcedSet(bool enforced);
    event FeeExemptSet(address indexed account, bool exempt);
    event AMMPairSet(address indexed pair, bool flagged);
    event MarketingWalletSet(address indexed wallet);
    event TradingEnabled(uint256 launchBlock, uint256 snipeBlocks);
    event SwapBackToggled(bool enabled);
    event SwapBackExecuted(uint256 tokensSwapped, uint256 bnbForMarketing, uint256 lpBurned);
    event SwapBackFailed();
    // Declared for ABI/indexer completeness; emitted by SwapLib in token
    // context (DELEGATECALL), so logs are attributed to the token address.
    event MarketingPaid(uint256 bnbAmount);
    event LiquidityAdded(uint256 tokenAmount, uint256 bnbAmount, uint256 lpBurned);

    /// @dev Single-struct constructor argument: avoids stack-too-deep and
    /// keeps the factory call-site unambiguous (no positional drift).
    struct TokenConfig {
        string name;
        string symbol;
        uint8 decimals;
        uint256 initialSupply;
        address owner;
        bool burnable;
        bool mintable;
        bool pausable;
        uint256 maxTxAmount; // 0 = disabled
        uint256 maxWalletAmount; // 0 = disabled
        bool blacklistEnabled;
        bool whitelistEnabled;
        // --- advanced ---
        uint256 buyTaxBps; // <= 1000 (10%)
        uint256 sellTaxBps; // <= 1000 (10%)
        address marketingWallet;
        uint256 marketingShareBps;
        uint256 liquidityShareBps;
        bool autoLiquidityEnabled;
        uint256 swapThreshold;
        bool antiBotEnabled;
        uint256 snipeBlocks; // <= 50
        uint256 maxSupply; // 0 = unlimited (explicit choice), else lifetime cap
    }

    constructor(TokenConfig memory config)
        ERC20(config.name, config.symbol)
        Ownable(config.owner)
    {
        if (config.owner == address(0)) revert ZeroAddress();
        // Full validation runs delegatecall'd in SwapLib (pure, identical
        // enforcement, smaller token init bytecode). Reverts here fail the
        // deployment closed — including cap misuse and tax misconfiguration.
        SwapLib.validateBasicConfig(
            config.name,
            config.symbol,
            config.decimals,
            config.initialSupply,
            config.maxTxAmount,
            config.maxWalletAmount
        );
        SwapLib.validateAdvancedConfig(
            config.buyTaxBps,
            config.sellTaxBps,
            config.marketingWallet,
            config.marketingShareBps,
            config.liquidityShareBps,
            config.autoLiquidityEnabled,
            config.swapThreshold,
            config.initialSupply,
            config.snipeBlocks,
            config.mintable,
            config.maxSupply
        );

        burnable = config.burnable;
        mintable = config.mintable;
        pausable = config.pausable;
        maxTxAmount = config.maxTxAmount;
        maxWalletAmount = config.maxWalletAmount;
        blacklistEnabled = config.blacklistEnabled;
        whitelistEnabled = config.whitelistEnabled;
        buyTaxBps = config.buyTaxBps;
        sellTaxBps = config.sellTaxBps;
        swapThreshold = config.swapThreshold;
        liquidityShareBps = config.liquidityShareBps;
        marketingShareBps = config.marketingShareBps;
        autoLiquidityEnabled = config.autoLiquidityEnabled;
        antiBotEnabled = config.antiBotEnabled;
        snipeBlocks = config.snipeBlocks;
        maxSupply = config.maxSupply;
        _decimals = config.decimals;
        FACTORY = msg.sender;

        _marketingWallet = config.marketingWallet;
        _tradingEnabled = !config.antiBotEnabled;

        if (config.whitelistEnabled) {
            _whitelisted[config.owner] = true;
        }
        // Owner, contract and (later) pairs settle exemptions explicitly;
        // the deployer starts exempt so seeding can never deadlock.
        _feeExempt[config.owner] = true;
        _feeExempt[address(this)] = true;
        emit FeeExemptSet(config.owner, true);

        _mint(config.owner, config.initialSupply);
        _totalMinted = config.initialSupply;
    }

    function decimals() public view override returns (uint8) {
        return _decimals;
    }

    // ---- views ----
    function paused() external view returns (bool) {
        return _paused;
    }

    function isBlacklisted(address account) external view returns (bool) {
        return _blacklisted[account];
    }

    function isWhitelisted(address account) external view returns (bool) {
        return _whitelisted[account];
    }

    function whitelistEnforced() external view returns (bool) {
        return _whitelistEnforced;
    }

    function feeExempt(address account) external view returns (bool) {
        return _feeExempt[account];
    }

    function marketingWallet() external view returns (address) {
        return _marketingWallet;
    }

    function tradingEnabled() external view returns (bool) {
        return _tradingEnabled;
    }

    function launchBlock() external view returns (uint256) {
        return _launchBlock;
    }

    function swapBackEnabled() external view returns (bool) {
        return _swapBackEnabled;
    }

    /// @notice Lifetime minted base units (burns excluded by design). Compare
    /// against `maxSupply` for remaining issuance, NOT against totalSupply().
    function totalMinted() external view returns (uint256) {
        return _totalMinted;
    }

    // ---- burn / mint / pause ----
    function burn(uint256 value) external {
        if (!burnable) revert FeatureDisabled("burn");
        if (value == 0) revert ZeroAmount();
        _burn(_msgSender(), value);
    }

    function burnFrom(address account, uint256 value) external {
        if (!burnable) revert FeatureDisabled("burn");
        if (value == 0) revert ZeroAmount();
        _spendAllowance(account, _msgSender(), value);
        _burn(account, value);
    }

    function mint(address to, uint256 value) external onlyOwner {
        if (!mintable) revert FeatureDisabled("mint");
        if (to == address(0)) revert ZeroAddress();
        if (value == 0) revert ZeroAmount();
        uint256 newTotal = _totalMinted + value;
        if (maxSupply > 0 && newTotal > maxSupply) {
            revert MaxSupplyExceeded(newTotal, maxSupply);
        }
        _totalMinted = newTotal;
        _mint(to, value);
    }

    function pause() external onlyOwner {
        if (!pausable) revert FeatureDisabled("pause");
        _paused = true;
        emit Paused(_msgSender());
    }

    function unpause() external onlyOwner {
        if (!pausable) revert FeatureDisabled("pause");
        _paused = false;
        emit Unpaused(_msgSender());
    }

    // ---- lists ----
    function setBlacklisted(address account, bool blocked) external onlyOwner {
        if (!blacklistEnabled) revert FeatureDisabled("blacklist");
        if (account == address(0)) revert ZeroAddress();
        // Blacklisting a flagged pair would block all sells: refuse on-chain.
        if (blocked && automatedMarketMakerPairs[account]) revert PairBlacklisted();
        _blacklisted[account] = blocked;
        emit BlacklistedSet(account, blocked);
    }

    function setWhitelisted(address account, bool allowed) external onlyOwner {
        if (!whitelistEnabled) revert FeatureDisabled("whitelist");
        if (account == address(0)) revert ZeroAddress();
        _whitelisted[account] = allowed;
        emit WhitelistedSet(account, allowed);
    }

    function setWhitelistEnforced(bool enforced) external onlyOwner {
        if (!whitelistEnabled) revert FeatureDisabled("whitelist");
        _whitelistEnforced = enforced;
        emit WhitelistEnforcedSet(enforced);
    }

    // ---- advanced: pair registry, exemptions, wallet, launch ----
    function setAMMPair(address pair, bool flagged) external onlyOwner {
        if (pair == address(0)) revert ZeroAddress();
        automatedMarketMakerPairs[pair] = flagged;
        if (flagged) {
            // A pair must hold concentrated balances and trade while lists
            // are enforced — but it is deliberately NOT added to _feeExempt:
            // exemption is reserved for explicit human/contract entries so a
            // future `_feeExempt` bypass can never silently cover the pair.
            // Pair privileges are hardcoded per path instead (maxWallet skip,
            // whitelist entry, side-aware tax/cooldown below).
            _whitelisted[pair] = true;
            emit WhitelistedSet(pair, true);
        }
        emit AMMPairSet(pair, flagged);
    }

    function setFeeExempt(address account, bool exempt) external onlyOwner {
        if (account == address(0)) revert ZeroAddress();
        _feeExempt[account] = exempt;
        emit FeeExemptSet(account, exempt);
    }

    function setMarketingWallet(address wallet) external onlyOwner {
        if (wallet == address(0)) revert ZeroAddress();
        _marketingWallet = wallet;
        emit MarketingWalletSet(wallet);
    }

    function enableTrading() external onlyOwner {
        if (!antiBotEnabled) revert FeatureDisabled("antibot");
        if (_tradingEnabled) revert TradingAlreadyEnabled();
        _tradingEnabled = true;
        _launchBlock = block.number;
        emit TradingEnabled(block.number, snipeBlocks);
    }

    function setSwapBackEnabled(bool enabled) external onlyOwner {
        // Operational breaker for the swap loop only: transfers always
        // process, with or without swapping.
        _swapBackEnabled = enabled;
        emit SwapBackToggled(enabled);
    }

    /// @notice Accepts BNB ONLY from the PancakeSwap router (swap proceeds).
    /// Direct BNB transfers revert: the contract is not a vault.
    receive() external payable {
        if (msg.sender != address(ROUTER)) revert RouterOnly();
    }

    // ---- transfer hook: all restrictions enforced in one place ----
    function _update(address from, address to, uint256 value) internal override {
        // Pause precedes everything: customer-controlled incident breaker.
        if (_paused) revert EnforcedPause();

        address owner = owner();

        if (blacklistEnabled) {
            if (_blacklisted[from] && to != address(0)) revert Blacklisted(from);
            if (_blacklisted[to]) revert Blacklisted(to);
        }

        if (whitelistEnabled && _whitelistEnforced) {
            if (to == address(0)) {
                // burn: always allowed (exit path).
            } else if (from == address(0)) {
                if (to != owner && !_whitelisted[to]) revert WhitelistEnforced();
            } else {
                if (from != owner && !_whitelisted[from]) revert WhitelistEnforced();
                if (to != owner && !_whitelisted[to]) revert WhitelistEnforced();
            }
        }

        if (antiBotEnabled && from != address(0) && to != address(0)) {
            if (!_tradingEnabled) {
                // Pre-launch: owner seeding and explicitly exempt
                // (non-pair) wallets move; all pair trading waits.
                bool fromOk = _feeExempt[from] && !automatedMarketMakerPairs[from];
                bool toOk = _feeExempt[to] && !automatedMarketMakerPairs[to];
                if (from != owner && to != owner && !(fromOk && toOk)) {
                    revert TradingDisabled();
                }
            } else if (block.number <= _launchBlock + snipeBlocks) {
                // Snipe window: one transfer per block for the non-pair side
                // of pair-involving transfers. Sells are never blocked.
                bool fromPair = automatedMarketMakerPairs[from];
                bool toPair = automatedMarketMakerPairs[to];
                if (fromPair != toPair) {
                    address user = fromPair ? to : from;
                    if (user != owner && !_feeExempt[user]) {
                        if (_lastTxBlock[user] >= block.number) revert CooldownActive();
                        _lastTxBlock[user] = block.number;
                    }
                }
            }
            // Post-window: no checks at all (cheapest path, permanent).
        }

        bool trading = from != address(0) && to != address(0);
        if (trading) {
            bool exemptLeg = _feeExempt[from] || _feeExempt[to];
            if (maxTxAmount > 0 && !exemptLeg && from != owner && to != owner) {
                if (value > maxTxAmount) revert MaxTxExceeded(value, maxTxAmount);
            }
            // Pairs bypass wallet caps (liquidity concentration), like owner.
            if (
                maxWalletAmount > 0 &&
                to != owner &&
                !automatedMarketMakerPairs[to] &&
                !exemptLeg
            ) {
                uint256 afterBalance = balanceOf(to) + value;
                if (afterBalance > maxWalletAmount) {
                    revert MaxWalletExceeded(to, afterBalance, maxWalletAmount);
                }
            }
        } else if (from == address(0) && to != address(0)) {
            if (maxWalletAmount > 0 && to != owner) {
                uint256 afterBalance = balanceOf(to) + value;
                if (afterBalance > maxWalletAmount) {
                    revert MaxWalletExceeded(to, afterBalance, maxWalletAmount);
                }
            }
        }

        // --- tax (buys/sells only, never mints/burns/wallet transfers) ---
        // Side-aware: the NON-pair counterparty is the taxed party, so the
        // pair's own limit/whitelist privileges never silence taxation.
        if (
            trading &&
            (buyTaxBps > 0 || sellTaxBps > 0) &&
            !_swapping &&
            from != address(this)
        ) {
            bool fromPair = automatedMarketMakerPairs[from];
            bool toPair = automatedMarketMakerPairs[to];
            uint256 bps = 0;
            if (fromPair && !toPair && !_feeExempt[to]) {
                bps = buyTaxBps;
            } else if (toPair && !fromPair && !_feeExempt[from]) {
                bps = sellTaxBps;
            }
            if (bps > 0) {
                uint256 tax = (value * bps) / 10000; // round down, dust stays
                if (tax > 0) {
                    super._update(from, address(this), tax);
                    value -= tax;
                }
            }
        }

        super._update(from, to, value);

        // --- swapBack trigger (post-transfer, never reverts the transfer).
        // Heavy execution lives delegatecall'd in SwapLib (no storage
        // coupling: explicit params only); the token keeps accounting.
        if (
            trading &&
            autoLiquidityEnabled &&
            !_swapping &&
            _swapBackEnabled &&
            (automatedMarketMakerPairs[from] || automatedMarketMakerPairs[to])
        ) {
            uint256 balance = balanceOf(address(this));
            address pair = automatedMarketMakerPairs[from] ? from : to;
            if (balance >= swapThreshold && SwapLib.pairHasLiquidity(pair)) {
                _swapping = true;
                try
                    SwapLib.executeSwap(
                        SwapLib.SwapArgs({
                            token: address(this),
                            marketingWallet: _marketingWallet,
                            liquidityShareBps: liquidityShareBps,
                            marketingShareBps: marketingShareBps
                        })
                    )
                {} catch {
                    emit SwapBackFailed();
                }
                _swapping = false;
            }
        }
    }
}
